image: "ruby:2.6.5"
stages:
  - test
  - build
  - deloy

cache:
  paths:
    - package.json
    - vendor/bundle
test:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"
    - bundle exec rubocop

build:
  stage: build
  script: echo "Building the app"

deloy:
  stage: deloy
  script: echo "Deloy the app"
